package com.lazoft.forwarderplus.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
@Getter
public enum CountryCode {
    Afghanistan("Afghanistan","+93"),
    Albania("Albania","+355"),
    Algeria("Algeria","+213"),
    AmericanSamoa("American Samoa","+1-684"),
    Andorra("Andorra","+376"),
    Angola("Angola","+244"),
    Anguill("Anguill","+1-264"),
    Antarctica("Antarctica","+672"),
    AntiguaBarbuda("Antigua and Barbuda","+1-268"),
    Argentina("Argentina","+54"),
    Armenia("Armenia","+374"),
    Aruba("Aruba","+297"),
    Australia("Australia","+61"),
    Austria("Austria","+43"),
    Azerbaijan("Azerbaijan","+994"),
    Bahamas("Bahamas","+1-242"),
    Bahrain("Bahrain","+973"),
    Bangladesh("Bangladesh","+880"),
    Barbado("Barbado","+1-246"),
    Belarus("Belarus","+375"),
    Belgium("Belgium","+32"),
    Belize("Belize","+501"),
    Benin("Benin","+229"),
    Bermuda("Bermuda","+1-441"),
    Bhutan("Bhutan","+975"),
    Bolivia("Bolivia","+591"),
    BosniaHerzegovina("Bosnia and Herzegovina","+387"),
    Botswana("Botswana","+267"),
    Brazil("Brazil","+55"),
    BritishIndianOcean("British Indian Ocean Territory","+246"),
    BritishVirginIslands("British Virgin Islands","+1-284"),
    Brunei("Brunei","+673"),
    Bulgaria("Bulgaria","+359"),
    Burkina("Burkina Faso","+226"),
    Burundi("Burundi","+257"),
    Cambodia("Cambodia","+855"),
    Cameroon("Cameroon","+237"),
    Canada("Canada","+1"),
    Cape("Cape Verde","+238"),
    Cayman("Cayman Islands","+1-345"),
    Central("Central African Republic","+236"),
    Chad("Chad","+235"),
    Chile("Chile","+56"),
    China("China","+86"),
    Christmas("Christmas Island","+61"),
    Cocos("Cocos Islands","+61"),
    Colombia("Colombia","+57"),
    Comoros("Comoros","+269"),
    Cook("Cook Islands","+682"),
    Costa("Costa Rica","+506"),
    Croatia("Croatia","+385"),
    Cuba("Cuba","+53"),
    Curacao("Curacao","+599"),
    Cyprus("Cyprus","+357"),
    Czech("Czech Republic","+420"),
    Democratic("Democratic Republic of the Congo","+243"),
    Denmark("Denmark","+45"),
    Djibouti("Djibouti","+253"),
    Dominica("Dominica","+1-767"),
    Dominican("Dominican Republic	1-809, 1-829,","+1-849"),
    EastTimor("East Timor","+670"),
    Ecuador("Ecuador","+593"),
    Egypt("Egypt","+20"),
    ElSalvador("El Salvador","+503"),
    Equatorial("Equatorial Guinea","+240"),
    Eritrea("Eritrea","+291"),
    Estonia("Estonia","+372"),
    Ethiopia("Ethiopia","+251"),
    FalklandIslands("Falkland Islands","+500"),
    FaroeIslands("Faroe Islands","+298"),
    Fiji("Fiji","+679"),
    Finland("Finland","+358"),
    France("France","+33"),
    FrenchPolynesia("French Polynesia","+689"),
    Gabon("Gabon","+241"),
    Gambia("Gambia","+220"),
    Georgia("Georgia","+995"),
    Germany("Germany","+49"),
    Ghana("Ghana","+233"),
    Gibraltar("Gibraltar","+350"),
    Greece("Greece","+30"),
    Greenland("Greenland","+299"),
    Grenada("Grenada","+1-473"),
    Guam("Guam","+1-671"),
    Guatemala("Guatemala","+502"),
    Guernsey("Guernsey	44","+1481"),
    Guinea("Guinea","+224"),
    GuineaBissau("Guinea-Bissau","+245"),
    Guyana("Guyana","+592"),
    Haiti("Haiti","+509"),
    Honduras("Honduras","+504"),
    Hong("Hong Kong","+852"),
    Hungary("Hungary","+36"),
    Iceland("Iceland","+354"),
    India("India","+91"),
    Indonesia("Indonesia","+62"),
    Iran("Iran","+98"),
    Iraq("Iraq","+964"),
    Ireland("Ireland","+353"),
    Isle("Isle of Man	44","+1624"),
    Israel("Israel","+972"),
    Italy("Italy","+39"),
    Ivory("Ivory Coast","+225"),
    Jamaica("Jamaica","+1-876"),
    Japan("Japan","+81"),
    Jersey("Jersey	44","+1534"),
    Jordan("Jordan","+962"),
    Kazakhstan("Kazakhstan","+7"),
    Kenya("Kenya","+254"),
    Kiribati("Kiribati","+686"),
    Kosovo("Kosovo","+383"),
    Kuwait("Kuwait","+965"),
    Kyrgyzstan("Kyrgyzstan","+996"),
    Laos("Laos","+856"),
    Latvia("Latvia","+371"),
    Lebanon("Lebanon","+961"),
    Lesotho("Lesotho","+266"),
    Liberia("Liberia","+231"),
    Libya("Libya","+218"),
    Liechtenstein("Liechtenstein","+423"),
    Lithuania("Lithuania","+370"),
    Luxembourg("Luxembourg","+352"),
    Macau("Macau","+853"),
    Macedonia("Macedonia","+389"),
    Madagascar("Madagascar","+261"),
    Malawi("Malawi","+265"),
    Malaysia("Malaysia","+60"),
    Maldives("Maldives","+960"),
    Mali("Mali","+223"),
    Malta("Malta","+356"),
    Marshall("Marshall Islands","+692"),
    Mauritania("Mauritania","+222"),
    Mauritius("Mauritius","+230"),
    Mayotte("Mayotte","+262"),
    Mexico("Mexico","+52"),
    Micronesia("Micronesia","+691"),
    Moldova("Moldova","+373"),
    Monaco("Monaco","+377"),
    Mongolia("Mongolia","+976"),
    Montenegro("Montenegro","+382"),
    Montserrat("Montserrat","+1-664"),
    Morocco("Morocco","+212"),
    Mozambique("Mozambique","+258"),
    Myanmar("Myanmar","+95"),
    Namibia("Namibia","+264"),
    Nauru("Nauru","+674"),
    Nepal("Nepal","+977"),
    Netherlands("Netherlands","+31"),
    NetherlandsAntilles("Netherlands Antilles","+599"),
    NewCaledonia("New Caledonia","+687"),
    NewZealand("New Zealand","+64"),
    Nicaragua("Nicaragua","+505"),
    Niger("Niger","+227"),
    Nigeria("Nigeria","+234"),
    Niue("Niue","+683"),
    NorthKorea("North Korea","+850"),
    Northern("Northern Mariana Islands","+1-670"),
    Norway("Norway","+47"),
    Oman("Oman","+968"),
    Pakistan("Pakistan","+92"),
    Palau("Palau","+680"),
    Palestine("Palestine","+970"),
    Panama("Panama","+507"),
    Papua("Papua New Guinea","+675"),
    Paraguay("Paraguay","+595"),
    Peru("Peru","+51"),
    Philippines("Philippines","+63"),
    Pitcairn("Pitcairn","+64"),
    Poland("Poland","+48"),
    Portugal("Portugal","+351"),
    Puerto("Puerto Rico	1-787,","+1-939"),
    Qatar("Qatar","+974"),
    Republic("Republic of the Congo","+242"),
    Reunion("Reunion","+262"),
    Romania("Romania","+40"),
    Russia("Russia","+7"),
    Rwanda("Rwanda","+250"),
    SaintBarthelemy("Saint Barthelemy","+590"),
    SaintHelena("Saint Helena","+290"),
    SaintKitts("Saint Kitts and Nevis","+1-869"),
    SaintLucia("Saint Lucia","+1-758"),
    SaintMartin("Saint Martin","+590"),
    SaintPierre("Saint Pierre and Miquelon","+508"),
    SaintVincent("Saint Vincent and the Grenadines","+1-784"),
    Samoa("Samoa","+685"),
    San("San Marino","+378"),
    Sao("Sao Tome and Principe","+239"),
    Saudi("Saudi Arabia","+966"),
    Senegal("Senegal","+221"),
    Serbia("Serbia","+381"),
    Seychelles("Seychelles","+248"),
    Sierra("Sierra Leone","+232"),
    Singapore("Singapore","+65"),
    Sint("Sint Maarten","+1-721"),
    Slovakia("Slovakia","+421"),
    Slovenia("Slovenia","+386"),
    Solomon("Solomon Islands","+677"),
    Somalia("Somalia","+252"),
    South("South Africa","+27"),
    SouthKorea("South Korea","+82"),
    SouthSuda("South Sudan","+211"),
    Spain("Spain","+34"),
    Sri("Sri Lanka","+94"),
    Sudan("Sudan","+249"),
    Suriname("Suriname","+597"),
    Svalbard("Svalbard and Jan Mayen","+47"),
    Swaziland("Swaziland","+268"),
    Sweden("Sweden","+46"),
    Switzerland("Switzerland","+41"),
    Syria("Syria","+963"),
    Taiwan("Taiwan","+886"),
    Tajikistan("Tajikistan","+992"),
    Tanzania("Tanzania","+255"),
    Thailand("Thailand","+66"),
    Togo("Togo","+228"),
    Tokelau("Tokelau","+690"),
    Tonga("Tonga","+676"),
    Trinidad("Trinidad and Tobago","+1-868"),
    Tunisia("Tunisia","+216"),
    Turkey("Turkey","+90"),
    Turkmenistan("Turkmenistan","+993"),
    Turks("Turks and Caicos Islands","+1-649"),
    Tuvalu("Tuvalu","+688"),
    USVI("U.S. Virgin Islands","+1-340"),
    Uganda("Uganda","+256"),
    Ukraine("Ukraine","+380"),
    UAE("United Arab Emirates","+971"),
    UK("United Kingdom","+44"),
    US("United States","+1"),
    Uruguay("Uruguay","+598"),
    Uzbekistan("Uzbekistan","+998"),
    Vanuatu("Vanuatu","+678"),
    Vatican("Vatican","+379"),
    Venezuela("Venezuela","+58"),
    Vietnam("Vietnam","+84"),
    Wallis("Wallis and Futuna","+681"),
    Western("Western Sahara","+212"),
    Yemen("Yemen","+967"),
    Zambia("Zambia","+260"),
    Zimbabwe("Zimbabwe","+263");

    private final String countryName;
    private final String countryCode;

}
