package com.lazoft.forwarderplus.enums;

public enum PackageUnit {
    AEROSOLS, BALES, BAGS, BASKETS, BOLTS, BOTTLES, BOARDS, BUCKETS, CAGES, CANS, CANISTERS, CARTONS, CASES, CASKETS,
    CASKS, CHESTS, COVERS, CRATES, CUPS, DRUMS, FLASKS, FRAMES, INGOTS, JARS, JUGS, JUTEBAGS, LOGS, MATS, NETS, PACKAGES,
    PALLETS, PARCELS, PIPES, RINGS, RODS, ROLLS, SACHETS, SACKS, SHEETS, SUITCASES, TANKS, TUBES, TUBS, TINS, VATS, VIALS
}