package com.lazoft.forwarderplus.enums;

public enum ShipmentStatus {
    NEW,
    STUFFING_DONE,
    SHIPMENT_ADVICE_SENT,
    BL_DRAFT_RECEIVED_FROM_SHIPPER,
    BL_DRAFT_SENT_TO_CARRIER,
    FINAL_BL_RECEIVED_FROM_CARRIER,
    INVOICE_RECEIVED_FROM_CARRIER,
    INVOICE_SENT_TO_SHIPPER,
    COMPLETED,
}
