server.port=${PORT:15070}
logging.level.org.atmosphere = warn

# Launch the default browser when starting the application in development mode
#vaadin.launch-browser=true
# PostgreSQL configuration.
spring.datasource.url = jdbc:postgresql://localhost:5432/forwarderdb
spring.datasource.username = postgres
spring.datasource.password = asdf1234
spring.jpa.hibernate.ddl-auto = update
# To improve the performance during development.
# For more information https://vaadin.com/docs/latest/integrations/spring/configuration#special-configuration-parameters
vaadin.allowed-packages = com.vaadin,org.vaadin,com.lazoft.forwarderplus
spring.jpa.defer-datasource-initialization = true
spring.sql.init.mode = always

exchange.api.url=https://v6.exchangerate-api.com/
exchange.api.version=v6
exchange.api.key=755aef81dcb40fc8baf23897
exchange.api.pair.conversion.endpoint=/pair

income.ledger.code=1
expense.ledger.code=2